picanto = {'M': 'TX1', 'L': 'TX2', 'BL': 'LX2', 'XL': 'LX3', 'GTL': 'SX1'}
ceed = {'S': 'TX1', 'M': 'TX2', 'L': 'TX3', 'BL': 'TX3_V00', 'GTL': 'LX1'}
ceed_kombi = {'S': 'TX1', 'M': 'TX2', 'L': 'TX3', 'BL': 'TX3_V00', 'GTL': 'LX1'}
ceed_kombi_phev = {'L': 'TX3', 'BL': 'TX3_V00', 'XL': 'TX2'}
proceed = {'GTL': 'TX3', 'GT': 'TX2'}
xceed = {'M': 'TX1', 'L': 'TX2', 'BL': 'TX3', 'GTL': 'LX1'}
xceed_phev = {'L': 'TX3', 'BL': 'LX1'}
stonic = {'M': 'TX1', 'L': 'TX2', 'BL': 'TX2_V00', 'GTL': 'TX3'}
niro_hev = {'HEV M': 'LX1', 'HEV L': 'TX1', 'HEV BL': 'SX1'}
niro_phev = {'PHEV M': 'LX2', 'PHEV L': 'TX2', 'PHEV BL': 'SX2'}
niro_ev = {'M': 'LX1', 'L': 'TX1', 'XL': 'SX1'}
e_soul = {'M': 'TX1', 'L': 'TX2', 'XL': 'TX3'}
sportage = {'M': 'LX2', 'L': 'LX3', 'BL': 'SX1', 'GTL': 'SX2'}
sportage_hev = {'HEV L': 'TX1', 'HEV BL': 'TX2', 'HEV GTL': 'TX3'}
sportage_phev = {'PHEV L': 'LX3', 'PHEV BL': 'SX1', 'PHEV GTL': 'SX3'}
sorento_hev = {'HEV M': 'TX1', 'HEV L': 'TX2', 'HEV XL': 'LX1', 'HEV PL': 'LX2'}
ev9 = {'EARTH RWD': 'SX1', 'GTL': 'SX3', 'EARTH AWD': 'TX2', 'GTL2': 'SX2'}
ev6 = {'EV6': 'TX1', 'EV6 PLUS': 'TX2', 'EV6 GTL': 'TX3'}
ev6_gt = {'EV6 GT': 'SX1'}

