from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from webtest_package.helpers.base import wait_to_be_visible
import time
from webtest_package.helpers.base import driver
from webtest_package.pages.home_page import HomePage
from webtest_package.pages.configurator_page import configurationPage
from webtest_package.helpers.base import converter_of_name
from webtest_package.helpers.car_data_list import ceed
from webtest_package.pages.car_config_page import carConfigPage
from webtest_package.helpers.car_data_list import picanto
from webtest_package.helpers.car_data_list import ceed_kombi
from webtest_package.helpers.car_data_list import ceed_kombi_phev
from webtest_package.helpers.car_data_list import proceed
from webtest_package.helpers.car_data_list import xceed
from webtest_package.helpers.car_data_list import xceed_phev
from webtest_package.helpers.car_data_list import stonic
from webtest_package.helpers.car_data_list import niro_hev
from webtest_package.helpers.car_data_list import niro_phev
from webtest_package.helpers.car_data_list import niro_ev
from webtest_package.helpers.car_data_list import e_soul
from webtest_package.helpers.car_data_list import sportage
from webtest_package.helpers.car_data_list import sportage_hev
from webtest_package.helpers.car_data_list import sportage_phev
from webtest_package.helpers.car_data_list import sorento_hev
from webtest_package.helpers.car_data_list import ev9
from webtest_package.helpers.car_data_list import ev6
from webtest_package.helpers.car_data_list import ev6_gt